In [1]:
import numpy as np

In [3]:
a=[1]
a

[1]

In [5]:
a0=np.array([1])
a1=np.array([5,4,3,2,1])
a2=np.array([[5,4,3,2,1],[5,4,3,2,1]])
a3=np.array([[[5,4,3,2,1],[5,4,3,2,1]],[[5,4,3,2,1],[5,4,3,2,1]]])


In [7]:
a0

array([1])

In [9]:
a1

array([5, 4, 3, 2, 1])

In [11]:
print(a2)

[[5 4 3 2 1]
 [5 4 3 2 1]]


In [13]:
print(a3)

[[[5 4 3 2 1]
  [5 4 3 2 1]]

 [[5 4 3 2 1]
  [5 4 3 2 1]]]


In [15]:
a0.shape

(1,)

In [17]:
a1.shape

(5,)

In [19]:
a2.shape

(2, 5)

In [21]:
a3.shape

(2, 2, 5)